server:
  port: 8084
spring:
  application:
    name: one
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    preferIpAddress: true
metrics:
  dir: business-services/one/src/main/resources/metrics/

resilience4j:
  retry:
    instances:
      flightSearch:
        maxRetryAttempts: 3
        waitDuration: 2s

resource:
  url:
   common: ${CONFIG_SERVER:http://localhost:8083/}
   two: ${TWO_SERVER:http://localhost:8083/}
